
// This file has been generated by the GUI designer. Do not modify.
namespace PiggySync.GtkGui
{
	internal class Gui
	{
		private static bool initialized;

		internal static void Initialize (Gtk.Widget iconRenderer)
		{
			if ((Gui.initialized == false)) {
				Gui.initialized = true;
				global::Gtk.IconFactory w1 = new global::Gtk.IconFactory ();
				global::Gtk.IconSet w2 = new global::Gtk.IconSet (new global::Gdk.Pixbuf (string.Format ("{0}{1}",System.AppDomain.CurrentDomain.BaseDirectory, "/PiggyLogo_64.png")));
				w1.Add ("logo64", w2);
				w1.AddDefault ();
			}
		}
	}
}
