
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Button forceSyncButton;
	
	private global::Gtk.Entry rootSyncPath;
	
	private global::Gtk.ProgressBar progressbar1;
	
	private global::Gtk.Button chooseFolderButton;
	
	private global::Gtk.CheckButton autoSyncCheckBox;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("PiGGY .... sync");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.CanFocus = true;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.forceSyncButton = new global::Gtk.Button ();
		this.forceSyncButton.CanFocus = true;
		this.forceSyncButton.Name = "forceSyncButton";
		this.forceSyncButton.UseUnderline = true;
		this.forceSyncButton.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.fixed1.Add (this.forceSyncButton);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.forceSyncButton]));
		w1.X = 13;
		w1.Y = 234;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rootSyncPath = new global::Gtk.Entry ();
		this.rootSyncPath.CanFocus = true;
		this.rootSyncPath.Name = "rootSyncPath";
		this.rootSyncPath.IsEditable = false;
		this.rootSyncPath.InvisibleChar = '●';
		this.fixed1.Add (this.rootSyncPath);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.rootSyncPath]));
		w2.X = 10;
		w2.Y = 191;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.progressbar1 = new global::Gtk.ProgressBar ();
		this.progressbar1.Name = "progressbar1";
		this.progressbar1.Text = "";
		this.progressbar1.Fraction = 0.73;
		this.progressbar1.PulseStep = 0.41;
		this.fixed1.Add (this.progressbar1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.progressbar1]));
		w3.X = 13;
		w3.Y = 142;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chooseFolderButton = new global::Gtk.Button ();
		this.chooseFolderButton.CanFocus = true;
		this.chooseFolderButton.Name = "chooseFolderButton";
		this.chooseFolderButton.UseUnderline = true;
		this.chooseFolderButton.Label = global::Mono.Unix.Catalog.GetString ("Choose");
		this.fixed1.Add (this.chooseFolderButton);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.chooseFolderButton]));
		w4.X = 181;
		w4.Y = 187;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.autoSyncCheckBox = new global::Gtk.CheckButton ();
		this.autoSyncCheckBox.CanFocus = true;
		this.autoSyncCheckBox.Name = "autoSyncCheckBox";
		this.autoSyncCheckBox.Label = global::Mono.Unix.Catalog.GetString ("AutoSync");
		this.autoSyncCheckBox.DrawIndicator = true;
		this.autoSyncCheckBox.UseUnderline = true;
		this.fixed1.Add (this.autoSyncCheckBox);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.autoSyncCheckBox]));
		w5.X = 149;
		w5.Y = 241;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 275;
		this.DefaultHeight = 276;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.forceSyncButton.Clicked += new global::System.EventHandler (this.OnForceSyncButtonClicked);
		this.chooseFolderButton.Clicked += new global::System.EventHandler (this.OnChooseFolderButtonClicked);
		this.autoSyncCheckBox.Toggled += new global::System.EventHandler (this.OnAutoSyncCheckBoxToggled);
	}
}
