// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace IosGui
{
	public partial class DeviacesTableVievControllerTableViewController : UITableViewController
	{
		public DeviacesTableVievControllerTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
