// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace IosGui
{
	public partial class LogTableViewController : UITableViewController
	{
		public LogTableViewController (IntPtr handle) : base (handle)
		{
		}

		public LogTableViewController () : base ()
		{
		}
	}
}
